project_id = "rfcwvwcxhgnjfawgpwbb"

[functions.admin-create-user]
verify_jwt = true

[functions.ai-chat]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false
import_map = "./import_map.json"

[functions.webpush-save]
verify_jwt = true